# Configuration for cargo-deny
# See full reference at https://embarkstudios.github.io/cargo-deny/index.html

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"

[licenses]
# We want to deny any crate with license set to "unknown"
unlicensed = "deny"
# Blanket allow/deny list
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "CC0-1.0",
    "ISC",
    "Zlib",
    "OpenSSL",
]
deny = [
    "GPL-1.0",
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
# We want to ensure we have a copy of license texts for all dependencies
copyleft = "warn"
allow-osi-fsf-free = "either"
default = "deny"

[bans]
# Deny multiple versions of same crate
multiple-versions = "warn"
# Deny wildcards in dependency paths
wildcards = "deny"
highlight = "all"
# List of crates to deny
deny = [
    # Security concerns
    { name = "openssl", version = "<3.0.0" },
    # Unmaintained
    { name = "git2", version = "<0.16.0" },
]

[sources]
# We only want dependencies from crates.io
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
