# Docker Compose configuration for SaaS UMKM platform (Simplified)
# File yang lebih sederhana untuk kebutuhan development sehari-hari

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: saas-postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-saas_umkm_db}
      POSTGRES_USER: ${DB_USER:-saas_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-saas_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - saas-network
    # Konfigurasi PostgreSQL minimal yang cukup untuk development
    command: [
      "postgres",
      "-c", "shared_buffers=1GB",
      "-c", "work_mem=16MB"
    ]

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    container_name: saas-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - saas-network
    # Konfigurasi Redis minimal
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  saas-network:
    driver: bridge
