services:
  - type: web
    name: saas-umkm-backend
    env: rust
    region: singapore
    plan: free
    buildCommand: cd backend && ./build.sh
    startCommand: cd backend && ./start.sh
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false # Ini akan diatur melalui Render dashboard
      - key: REDIS_URL
        sync: false # Ini akan diatur melalui Render dashboard
      - key: JWT_SECRET
        sync: false # Ini akan diatur melalui Render dashboard
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        fromService:
          type: web
          name: saas-umkm-backend
          envVarKey: PORT
      - key: ENABLE_RATE_LIMITING
        value: "false" # Disable rate limiting sementara untuk testing
      - key: ENABLE_COMPRESSION
        value: "true"
      - key: RUST_LOG
        value: info

  - type: web
    name: saas-umkm-frontend
    env: node
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: saas-umkm-backend
          property: url
      - key: PORT
        value: 3000

databases:
  - name: saas-umkm-db
    plan: free
    region: singapore
    databaseName: saas_umkm_db
    user: saas_user

  - name: saas-umkm-redis
    plan: free
    region: singapore
    ipAllowList: [] # allow all connections
